name: clean_code
description: "save your time with clean code"
version: 1.0.1
homepage: https://marhaendev.com
repository: https://github.com/marhaendev/clean_code


environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
